language: csharp
solution: Creatures.sln
install:
  - nuget restore Creatures.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Creatures.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe /home/travis/build/AlexanderMishutkin/creatures/CreaturesLibrary.Test/CreaturesLibrary.Test/bin/Release/netcoreapp2.0/CreaturesLibrary.Test.dll