language: csharp
solution: Creatures.sln
install:
  - nuget restore Creatures.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Creatures.sln
  - ls /home/travis/build/AlexanderMishutkin/creatures
  - ls /home/travis/build/AlexanderMishutkin/creatures/CreaturesLibrary.Test
  - ls /home/travis/build/AlexanderMishutkin/creatures/CreaturesLibrary.Test/CreaturesLibrary.Test
  - ls /home/travis/build/AlexanderMishutkin/creatures/CreaturesLibrary.Test/CreaturesLibrary.Test/bin
  - ls /home/travis/build/AlexanderMishutkin/creatures/CreaturesLibrary.Test/CreaturesLibrary.Test/bin/Release
  - ls /home/travis/build/AlexanderMishutkin/creatures/CreaturesLibrary.Test/CreaturesLibrary.Test/bin/Release/netcoreapp2.0
  - cp /home/travis/build/AlexanderMishutkin/creatures/CreaturesLibrary.Test/CreaturesLibrary.Test/bin/Release/netcoreapp2.0/CreaturesLibrary.Test.dll /home/travis/build/AlexanderMishutkin/creatures/CreaturesLibrary.Test/CreaturesLibrary.Test/bin/Release/netcoreapp2.0/xunit.dll
  - ls /home/travis/build/AlexanderMishutkin/creatures/CreaturesLibrary.Test/CreaturesLibrary.Test/bin/Release/netcoreapp2.0
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe /home/travis/build/AlexanderMishutkin/creatures/CreaturesLibrary.Test/CreaturesLibrary.Test/bin/Release/netcoreapp2.0/CreaturesLibrary.Test.dll